title: Malla interactiva icf
description: Ingeniería civil física
theme: jekyll-theme-primer


url: https://iache-d.github.io/malla-interactiva-icf/
baseurl: /malla-interactiva-icf

markdown: kramdown
plugins:
  - jekyll-feed
